# Generated by Django 3.2.10 on 2022-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEACHER', 'Teacher'), ('HR', 'HR')], default='EMPLOYEE', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='_role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEACHER', 'Teacher'), ('HR', 'HR')],
                                   default='EMPLOYEE', max_length=10),
        ),
    ]
