version: '3.7'
services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    environment:
      - HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432

  django:
    build: .
    command: /bin/bash -c "exec invoke run-local"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env
