version: '3.7'
services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    environment:
      - HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432

  django:
    build: .
    command: /bin/bash -c "exec invoke run-local"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/code
    expose:
      - 8000

  react:
    image: node:16.17
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: bash -c "npm install && npm start"

  nginx:
    image: nginx:latest
    expose:
      - 8000
      - 3000
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - django
      - react
    volumes:
      - ./nginx/setup_nginx.conf:/etc/nginx/conf.d/web.conf
