version: '3.7'
services:
  django:
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:12
    environment:
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432