version: '3.7'
services:
  django:
    build: .
    command: python3 ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#    working_dir: /code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - USER_NAME=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - HOST=${HOST}

  postgres:
    image: postgres:12
    env_file:
      - .env
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432