# Generated by Django 3.2.10 on 2022-08-18 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import english.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('days', english.models.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, default=list, size=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('students', models.ManyToManyField(related_name='student_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', models.CharField(choices=[('COMING', 'Coming soon..'), ('PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='COMING', max_length=15)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='english.class', verbose_name='class_name')),
            ],
            options={
                'verbose_name_plural': 'Lessons',
                'ordering': ['time_start'],
            },
        ),
    ]
