# Generated by Django 3.2.10 on 2022-06-26 18:18

from django.db import migrations, models
import django.db.models.deletion
import english.models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', english.models.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10), blank=True, default=list, size=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='english.class', verbose_name='Class name')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
