# Generated by Django 3.2.10 on 2022-08-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['start_time'], 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
