# Generated by Django 3.2.10 on 2022-07-23 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', models.CharField(choices=[('COMING', 'Coming soon..'), ('PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='COMING', max_length=15)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.class', verbose_name='class_name')),
            ],
            options={
                'ordering': ['time_start'], 'verbose_name_plural': 'Lessons'
            },
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
