# Generated by Django 3.2.10 on 2022-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_rename_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
